### ISSUE TITLE
Use Rhino in Marcin's project

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/rhino#178]
Create a PR which introduces Rhino to Marcin's project. Perhaps not with all functionalities - use the simplest possible configuration.

**Comment by kamilzyla** [comment]
I took a look at the [wbtv](https://github.com/Appsilon/wbtv) repository today: launched the app and investigated its structure. The following steps should be sufficient to introduce Rhino in basic capacity:
1. Move the contents of `src` level up.
2. Drop `.Rprofile`, `.renvignore`, `app.R`, `src.Rproj`. Rhino will create its own.
3. Run `rhino::init()`.
4. Set `legacy_entrypint: app_dir` in `rhino.yml`.

You should now be able to run `shiny::runApp()` in project root.

**Comment by kamilzyla** [comment]
Agreed with @mdubel that he will attempt to migrate the app with help from @jakubnowicki.

**Comment by mdubel** [comment]
Notes:
1. Moving files app and starting a new project made RStudio confused.
2. Installing rhino without project took long time
3. There is no `rhino.yml` file ?
4. Maybe because in `init` I got an error about sass file already exists ?
5. Try `init` again. Error that `.renvignore` exists. Remove, try again: 
Error in mapply(renv_lockfile_diff_impl, old, new, MoreArgs = list(compare = compare),  : 
  zero-length inputs cannot be mixed with those of non-zero length
6. `renv::snapshot` is producing that error.
7. Trying to re-initialize `renv::init`. Same error.
8. More renv::clean, deactivate
9. `rhino::init` again. .renvignore problem again. Removed. Now error because `index.js` already exists.
10. Remove js, renvignore problem again :D
11. Error ./app/logic/__init__.R exists. I see a pattern here
12. I though I removed everything, rhino::init again. Error `app/main.R` already exists. Kill me please
13. One more approach and finally init is done! And now there is `rhino.yml` file. Edited with legacy entrypoint
14. Error, Kamil made a typo above and I just copy pasted :D 
```
> shiny::runApp()
Error in value[[3L]](cond) : 
  Package ‘glue’ version 1.6.2 cannot be unloaded:
 Error in unloadNamespace(package) : namespace ‘glue’ is imported by ‘tidyselect’, ‘dplyr’, ‘pillar’ so cannot be unloaded
 ```
 Come on, `glue` is doing one job only, how this can cause problems :(
 15. Restart session. Always a good idea.
 16. Ok, now I see how my app looks without any styling. Not good, I'll try to bring my styles back.
 17. It seems that `main.scss`, the one that caused my so many issues that it existed, is now empty. 
 18. Ok, I brought back my old code and the styles are back in business, great. But they're still coming from old /www folder. Nothing was created in /static. Ok, this is next step, goal one achieved: app works.

**Comment by mdubel** [comment]
1. Ok, CI works, linting problems found 👍 
2. I'd like to organise css and js and I found this confusing. First, my scss source files should be stored in /styles, but the minified file will be stored in /stats. For JS there is an `index.js` in /js, but my source files are now in /www/js. Where my minified should be? It will be index.js or something newly created that will be in /static ?
3. Confusion with `yarn`. `build_js()` returns yarn error, but gives no help of how that can be solved. Now I'll go to google to how install yarn, but `rhino` is not helping here.
4. Node is not there, and installing it on Clients workbench requires some WB devops. But there is some `.rhino` folder with `node` inside, I'm confused.
5. Default option for `sass: node` is not fine.
6. With Kuba trying to move app to the `source` legacy level. That requires multiple changes, as it forces lack of server and ui files.
7. I'm still having issues with files location. It requires a lot of changes.
8. I get another problem. The things that we used to have in `global.R` are now a part of `main.R`, but they are not loaded the same way, i.e. they do not exist in global scope. Those are basically just constants for getting the correct DB for particular environment (dev, test, prod). Now I would need to reorganise the logic in whole app to use them differently. No way. I go back to `app_dir` level.
9. I have issues with getting and storing data with the new structure. There is a lot of DB connection / local storing and caching logic in the app.
10. Side note: I see that in github actions there is a fixed R_VERSION 4.1.0 set, while we are using 4.0.3 in app. I hope I can just modify this in `rhino-test.yml` and it will be ok.

**Comment by mdubel** [comment]
Ok, so for now what I did and decide:
1. I give up with using `rhino::init`, even thought I was able to make app start (on the `app_dir`, not `source` level).
2. I decided for this as moving the files around seemed too risky and making too much chaos (e.g. to merge all the heavy logic being developed in the meantime). This project is also not-standard as it caches a lot of content and actual structure is important.
3. I was also worried about the Connect deployment: we are updating the same deployment, triggered from the `server.R` level. Settings for deployed version need to be set by WB people, as we are lacking rights. 
4. I moved only the functionalities that are crucial for the project: tests structure (including cypress) and github actions. I had to manually place them, as I understand there is no way in rhino to just add single functionality. Now I need to edit them for the current structure.
5. With all the rhino structure in mind, we will gradually modify the code to make it more ready, e.g. when we feel it is save we might move the code structure. It might be hard on the stage of the project, however it is also not super advanced (5 months of work, no production version yet).

**Comment by mdubel** [comment]
`lint_js` does not allow me to specify the path, it has to be `app/js`. I need to get rid of this for now.
`lint_sass` does not allow me to specify number of accepted errors (and there are tons of it - I don't think our sass is so bad, there is some `no-descending-specificity` mentioned a lot, I need to read more about it). I need to get rid of this for now.
`Run Cypress` a, that is why `.rhino/node` is there. I might need to bring it back as well. So I wish there is just an option now `rhino::add_cypress`
