### ISSUE TITLE
`build_sass()` fails due to InvalidOption

### ISSUE THREAD

**Issue by sdadsetan-concert** [Appsilon/rhino#429]
Running `build_sass()` yields this error and presumably because the sass option should be `sass --sourcemap=none` rather than `--no-source-map`

```
OptionParser::InvalidOption: invalid option: --no-source-map
Did you mean?  sourcemap
  Use --trace for backtrace.
Error in `value[[3L]]()`:
! System command 'npm' exited with status 1.
ℹ If you can't use Node.js, try using sass: 'r' configuration.
Run `rlang::last_error()` to see where the error occurred.
```

https://github.com/Appsilon/rhino/blob/5d85649b14ebe16770a2dbe350573e298ce10497/inst/templates/node/package.json#L5

**Comment by Leszek-Sieminski** [comment]
Hello, Sep! Thank you for submitting this issue!
Could you run the function `rhino::diagnostics()` and paste the output here?

**Comment by sdadsetan-concert** [comment]
Sure thing. Here you go:

```
> rhino::diagnostics()
Linux 5.15.0-1026-aws #30~20.04.2-Ubuntu SMP Fri Nov 25 14:53:22 UTC 2022
R version 4.1.1 (2021-08-10)
rhino: 1.3.0
node: v18.13.0
````

**Comment by Leszek-Sieminski** [comment]
Thanks! Unfortunately we cannot reproduce your issue. It looks like it is caused by different implementation of `sass`: Rhino uses locally installed `dart-sass` but your error comes from `ruby-sass`.

We're not sure how is this happening, maybe somehow local  folder `dart-sass` got changed/deleted so `npm` tries to used global installation of `ruby-sass` instead?

Can you do the following to help us understand the problem better:

1. create a new and clean directory
2. enter it and initialise new empty Rhino app (for example with `rhino::init()`)
3. run `rhino::build_sass()`
4. let me know in this thread if the problem still occurs there?

**Comment by sdadsetan-concert** [comment]
So I removed the `ruby-sass` installation from our Ubuntu server and followed your instructions above. Unfortunately when I ran `rhino::build_sass()` the first time it just hung there and didn't give the console back. I'm going to assume it's because I didn't have any content in the `main.scss` file. Not sure. After I added something though, things seem to be operational. Thanks for your help! Excited to use this framework.

**Comment by sdadsetan-concert** [comment]
I know this is closed, but finally got back to exploring a bit more. I didn't have any other modules installed (locally or globally) that might interfere with the `build_sass()` command, but I was able to fix by removing the `node_modules` folder and reinstalling with `npm install`. This makes me think it has something to do with the init of the rhino project, but requires further examination. Just thought I'd put this here in case someone comes across a similar issue.
