### ISSUE TITLE
Rhino favicon remains despite deletion

### ISSUE THREAD

**Issue by asadow** [Appsilon/rhino#563]
### Steps to reproduce

1. Delete favicon.ico
2. `rhino::app()`
3. Expand to browser if needed

### Bug description

The rhino favicon remains after deletion.

### Expected behavior

The rhino favicon should be removed or replaced.

**Comment by kamilzyla** [comment]
Thanks for reporting this @asadow! The behavior you have encountered is due to caching done by the browser and not specific to Rhino. To see the updated/deleted favicon, hard-refresh the page (Ctrl+Shift+R or Ctrl+F5).

There are [ways to control caching](https://stackoverflow.com/questions/728616/disable-cache-for-some-images) which could prevent the issue, but I don't think the added complexity would justify the benefits. I'm going to close this one.
