### ISSUE TITLE
Automated E2E tests for rhino package

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/rhino#58]
The test should:
1. Test on Linux, Windows & MacOS.
2. Run `rhino::init()` and check that the app can be launched.

Consider if this can be simply a testthat test. Possible inspiration: [shiny.benchmark](https://github.com/Appsilon/shiny.benchmark/blob/develop/.github/workflows/tests.yml).

***

### `init()`

1. A Rhino directory should be created.
2. Github Actions CI should not be added when specified, `github_actions_ci = FALSE`.
3. A specific Rhino version should be installed with `rhino` parameter.

###  `lint_r()`

1. Files in `app` and `tests` should be linted.
2. Specific files or directories (when `paths` is specified) should be linted.

### `test_r()` - side effect only, but might be testable using snapshot

1. All passing tests should return no failures.
2. Tests with failures should be captured properly.

### `build_js()`

1. Correct `app/static/js/app.min.js` should be built.
2. Tentative: `app/static/js/app.min.js` should build when source files changes and `watch = TRUE`.

### `build_sass()`

1. Correct `app/static/css/app.min.css` should be built.
2. Tentative: `app/static/css/app.min.css` should build when source files changes and `watch = TRUE`.

### `lint_sass()` and `lint_js()`

1. No errors should be reported when there are no lint errors.
2. Lint errors should be detected when they are present.
3. Lint errors should be fixed when `fix = TRUE`.

### `test_e2e()`

1. Correct cypress tests should run and succeed.
2. Cypress tests with failures should fail as expected.

**Comment by vibalre** [comment]
# Issues with `rhino::test_r()`

Unlike the other Rhino functions, I can't make `rhino::test_r()` work in the e2e pipeline work. The other functions only need to be pointed to the right directory. In this case, the workflow creates a `RhinoApp` directory in `tests/e2e`.

The working directory is set to `./tests/e2e` because all the test scripts needed for the workflow are in there. Just changing the directory to `tests/e2e/RhinoApp` and running `rhino::test_r()` will not work because the `.Rprofile` is not loaded.

I tested locally, restarting the R session then opening the created Rhino app in another session. However, when I run `rhino::test_r()` I still get the same error.

```
rhino::test_r()
Starting 1 test process
✔ | F W S  OK | Context
⠇ [ FAIL 0 | WARN 0 | SKIP 0 | PASS 0 ] Starting up...                                                                                                                                      

Error in `private$handle_error()`:
! testthat subprocess failed to start, stderr:
Error in getNamespace(ns) : attempt to use zero-length variable name
Calls: callr_startup_hook ... check_environment -> is_environment -> asNamespace -> getNamespace
Caused by error:
! R session crashed with exit code 1
Run `rlang::last_trace()` to see where the error occurred.
```

When I try `testthat::test_local()` I get test results, but it is not running the tests in `RhinoApp` but the tests of the package.

```
testthat::test_local()
Starting 2 test processes
✔ | F W S  OK | Context
✔ |        10 | config [0.2s]                                                                                                                                                               
✔ |         7 | app [0.2s]                                                                                                                                                                  
✔ |         3 | rhino                                                                                                                                                                       
                                                                                                                                                                                            
══ Results ═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 1.8 s

[ FAIL 0 | WARN 0 | SKIP 0 | PASS 20 ]
```

I have also tried using `withr::with_dir()` but that returns the same error as above, `! testthat subprocess failed to start`.

I had an idea to use `actions/checkout@v3`, but that only works when the directory is already available in the repository, i.e. not created in the workflow.

**Comment by kamilzyla** [comment]
@vibalre Thanks for the description of problems with `test_r()`! I did some testing and find it quite puzzling. Still not sure of the root cause; gonna play with it more.

Right now, our Rhino E2E tests are mostly independent. Moving forward we can start thinking about them as a single scenario - a simulation of how the package could be used. To be more specific, the test could for example:
1. Add some R (use `lint_r()` and `format_r()`).
2. Add some JS (use `lint_js()` and `build_js()`).
3. Add some CSS (use `lint_sass`() and `build_sass()`).
4. Add a Cypress test which will verify the R, JS and CSS added in the previous steps (use `test_e2e()`).

This will add complexity, but it will allow for more robust and comprehensive testing. Examples:
1. Instead of comparing the result of `build_js()` to a fixed file (which can break easily), we can check that the built JS actually works.
2. We could test complex features, like `legacy_entrypoint` setting or Shiny bookmarking support.
