### ISSUE TITLE
Build JS & Sass in CI

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/rhino#92]
### Problem
Currently the CI of a Rhino app only runs linters for JS and Sass (`lint_js()`, `lint_sass()`), but doesn't build it (`build_js()`, `build_sass()`). An issue which breaks the build but is not detected by the linters can go unnoticed.

### Goal
Run `build_js()` and `build_sass()` in Rhino app CI.

### Details
The relevant code is `inst/templates/github_ci/dot.github/workflows/rhino-test.yml`.

To test:
1. Create a new [orphan branch](https://stackoverflow.com/a/4288660/15981712) in the [rhino-showcase](https://github.com/Appsilon/rhino-showcase) repo.
2. Push a freshly initialized Rhino app.
3. Introduce a change which passes the linters but breaks the build.
4. Verify that the issue is detected by the CI and link the runs in the PR.

**Comment by vibalre** [comment]
Here is an example of [lint passing but build failing for Sass](https://github.com/Appsilon/rhino-showcase/actions/runs/3278440602).

Later in the workflow, Cypress also fails, and I have no idea why.

**Comment by vibalre** [comment]
This is an example of a [build failing for JS](https://github.com/Appsilon/rhino-showcase/actions/runs/3279754162/jobs/5399695091)

Note; I had to remove the lint for JS because I could not find or create a script that will pass `rhino::lint_js()` but fail `rhino::build_js()`, so this test is more of a proof that `rhino::build_js()` will throw an error in CI.
